### ISSUE TITLE
OpenAQ

### ISSUE THREAD

**Issue by RocketD0g** [okfn/dataportals.org#103]
`* Required`

# Key Data Portal Information
---
## Title *
Global, real-time open government air quality data

## URL *
https://openaq.org

## Manager
OpenAQ

## Description *
This platform aggregates global air quality data in near-real-time from public government sources and puts the data into one format. If you'd like to get involved in our community, share how you're using the data, help improve the platform, or have questions, contact us at info@openaq.org or join our Slack channel: https://openaq-slackin.herokuapp.com/

FAQ's on our platform can be found here:
https://github.com/openaq/openaq-info/blob/master/FAQ.md

If you use our platform for some purpose, let us know, so we can feature you on our Community Page! https://openaq.org/#/community

# Additional Information
## Place *
International; a current list of countries we aggregate from can be found here: https://openaq.org/#/countries?_k=qe5vfl

## License *
Data: CC-By, Software: MIT License

## License details
https://github.com/openaq/openaq-api/blob/develop/LICENSE.md

## Type *
The open-source portal is operated by OpenAQ and its community, and it serves a wide swath of the public interested in air inequality issues, from those in policy, academia, media, tech, and education sectors. 

## Launched
06/01/2015

## Portal Software
https://github.com/openaq

## Portal Software details
If you'd like to see a 20 minute video explaining the software 'guts' of our platform, view it here: https://medium.com/@openaq/ever-wonder-what-is-under-the-hood-of-the-openaq-platform-and-how-to-help-build-off-of-it-927b622fcdc2

## API Type *
Data can be accessed via the following methods:

- Use [our open API](https://docs.openaq.org)
- [Download data by csv](https://openaq.org/#/countries) 
- You can [build you own air quality comparisons](https://openaq.org/#/compare/MNB/Beijing%20US%20Embassy/Anand%20Vihar?parameter=pm25) of stations around the world.
- Check out the [global map](https://openaq.org/#/map) 
- [Daily CSV dumps](https://openaq-data.s3.amazonaws.com/index.html)
- [Daily PostgeSQL database snapshots](https://github.com/openaq/oh-snap) on Amazon RDS

## API Endpoint
https://api.openaq.org/v1/

## Full metadata download
https://openaq-data.s3.amazonaws.com/index.html

For more options or if this doesn't meet your need, see FAQ B14: 
https://github.com/openaq/openaq-info/blob/master/FAQ.md

Or contact us at: info@openaq.org

# Your Information
## Your Name
Christa Hasenkopf

## Your Email
christa@openaq.org

## Your Link
https://twitter.com/Open_AQ

**By submitting material in this issue you agree to:**

A. The terms of use - https://okfn.org/terms-of-use/

B. To place your contribution in the public domain (specifically you "license" any rights you may have under the CCZero - http://creativecommons.org/publicdomain/zero/1.0/ and/or the Open Data Commons Public Domain Dedication and License - http://opendatacommons.org/licenses/pddl/1.0/).

This latter enables us, in turn, to make available the resulting database openly available as per the Open Definition - http://opendefinition.org/od/.

**Comment by todrobbins** [comment]
Thank you @RocketD0g! We'll get you added ASAP

**Comment by Mikanebu** [comment]
@todrobbins FIXED in https://github.com/okfn/dataportals.org/pull/158. Please, close it

**Comment by Mikanebu** [comment]
FIXED in #158
