### ISSUE TITLE
Boundaries for US Hunting and Public Lands

### ISSUE THREAD

**Issue by andrewljohnson** [okfn/dataportals.org#107]
`* Required`

# Key Data Portal Information
---
## Title *

OpenBounds - Boundaries for US Hunting and Public Lands

## URL *

https://github.com/openbounds

## Manager

Trailbehind, Inc.

## Description *

Aggregates data for boundaries, provides schema for adding data to project.

# Additional Information
## Place *

United States

## Country

United States

## License *

MIT

## License details

None

## Type *

Created by a company, MIT licensed.

## Launched

10/19/2015

## Portal Software

github.com

## Full metadata download

# Your Information
## Your Name

Gaia GPS

## Your Email

andrew@gaiagps.com

## Your Link

gaiagps.com

**By submitting material in this issue you agree to:**

A. The terms of use - https://okfn.org/terms-of-use/

B. To place your contribution in the public domain (specifically you "license" any rights you may have under the CCZero - http://creativecommons.org/publicdomain/zero/1.0/ and/or the Open Data Commons Public Domain Dedication and License - http://opendatacommons.org/licenses/pddl/1.0/).

This latter enables us, in turn, to make available the resulting database openly available as per the Open Definition - http://opendefinition.org/od/.

**Comment by todrobbins** [comment]
Thank you @andrewljohnson! We'll get this added ASAP.

**Comment by Mikanebu** [comment]
FIXED in #158
