### ISSUE TITLE
data.go.kr - Official South Korea Government Data Portal

### ISSUE THREAD

**Issue by sharkbatt** [okfn/dataportals.org#118]
`* Required`

# Key Data Portal Information
---
## Title *

data.go.kr - Official South Korea Government Data Portal
## URL *

http://data.go.kr/
## Manager

NIA (National Information Society Agency)
## Description *

The South Korea's official open data catalogue.
# Additional Information
## Place *

South Korea
## Full metadata download

# Your Information
## Your Link

**By submitting material in this issue you agree to:**

A. The terms of use - https://okfn.org/terms-of-use/

B. To place your contribution in the public domain (specifically you "license" any rights you may have under the CCZero - http://creativecommons.org/publicdomain/zero/1.0/ and/or the Open Data Commons Public Domain Dedication and License - http://opendatacommons.org/licenses/pddl/1.0/).

This latter enables us, in turn, to make available the resulting database openly available as per the Open Definition - http://opendefinition.org/od/.

**Comment by todrobbins** [comment]
Thank you @sharkbatt!

**Comment by sharkbatt** [comment]
Hello, Mr. Robbins

Thank you for your contribution

I found that the map of dataportals.org's main page shows **wrong location of two portals**

**1. 'data.go.kr'**
url : data.go.kr
dataportals.org url : http://dataportals.org/portal/data_go_kr
location : **Daegu, South Korea(Rep. of Korea)**
latitude : 35.880886
longitude : 128.730030


**2.'datahub.kr'**
url : datahub.kr
dataportals.org url : http://dataportals.org/portal/korea-datahub
location : **Seoul, South Korea(Rep. of Korea)**
latitude : 37.566524
longitude : 126.977936

I'd appreciate it if you check and correct it.

**Comment by todrobbins** [comment]
Hi @sharkbatt! I corrected those with #127
