### ISSUE TITLE
Dataplatform, all your data at one place

### ISSUE THREAD

**Issue by MariskaSchepers** [okfn/dataportals.org#119]
Dataplatform, all your data at one place
---
## Title 
Dataplatform.nl

## URL 
www.dataplatform.nl

## Manager
Civity B.V.

## Description 
With Dataplatform.nl all your data is at one place. In Dataplatform, the publication of data is elementary, the findability improves, the quality is better and it improves usability and applicability. Efficient and uniform sharing of data. Developing together is the keyword.

# Additional Information
## Place 
Zeist, Netherlands

## Country
NL

## Type
government , research, other and community

## Full metadata download

# Your Information
## Your Link

**By submitting material in this issue you agree to:**

A. The terms of use - https://okfn.org/terms-of-use/

B. To place your contribution in the public domain (specifically you "license" any rights you may have under the CCZero - http://creativecommons.org/publicdomain/zero/1.0/ and/or the Open Data Commons Public Domain Dedication and License - http://opendatacommons.org/licenses/pddl/1.0/).

This latter enables us, in turn, to make available the resulting database openly available as per the Open Definition - http://opendefinition.org/od/.

**Comment by Mikanebu** [comment]
FIXED in #158
