### ISSUE TITLE
Slim Melden

### ISSUE THREAD

**Issue by MariskaSchepers** [okfn/dataportals.org#120]
Slim Melden (Smart reporting)
---
## Title
Slim Melden

## URL
http://www.civity.nl/?producten=makkelijk-melden

## Manager
Civity B.V.

## Description
Slim Melden, “smart reporting’’ helps organizations in streaming notifications and handling them with smart use of open data. Improve service and efficiency increases the involvement of the citizen. Slim Melden improves the entire process, is open and very user-friendly.

# Additional Information
## Place 
Zeist, Netherlands

## Country
NL, EU

## Type
Govermant, cities, citizen, community

## Full metadata download

# Your Information
## Your Link

**By submitting material in this issue you agree to:**

A. The terms of use - https://okfn.org/terms-of-use/

B. To place your contribution in the public domain (specifically you "license" any rights you may have under the CCZero - http://creativecommons.org/publicdomain/zero/1.0/ and/or the Open Data Commons Public Domain Dedication and License - http://opendatacommons.org/licenses/pddl/1.0/).

This latter enables us, in turn, to make available the resulting database openly available as per the Open Definition - http://opendefinition.org/od/.

**Comment by rufuspollock** [comment]
@MariskaSchepers is this actually a data portal or just a tool. dataportals.org focuses on listing portals not tools.

**Comment by Mikanebu** [comment]
@MariskaSchepers Seems like, it is not a data portal. We will close it as INVALID.

**Comment by Mikanebu** [comment]
INVALID, it is not considered as a data portal
