### ISSUE TITLE
Open Data Portal of Banda Aceh Municipal

### ISSUE THREAD

**Issue by antoub** [okfn/dataportals.org#121]
`* Required`

# Key Data Portal Information
---
## Title *

data.bandaacehkota.go.id - Open Data Portal of Banda Aceh Municipality 
## URL *

http://data.bandaacehkota.go.id/

## Manager

T. Taufik M.

## Description *

The ODBA Portal (Open Data Banda Aceh) is a portal service of Banda Aceh Municipal Open Data Catalog which aims to facilitate the public in obtaining data with open data format. Hopefully this application provides benefits for the development of Banda Aceh City in particular and the general public at large.
# Additional Information
## Place *

Banda Aceh, Aceh
## Country

ID
## License *

CCA
## Type *

Government
## Launched

12/01/2015
## Portal Software

Custom
## Portal Software details

Codeigniter PHP Framework with MySQL Database backend.
## API Type *

POST/GET API
## API Endpoint

http://data.bandaacehkota.go.id/index.php/api/action/site_read
## Full metadata download

http://data.bandaacehkota.go.id/index.php/api/action/current_package_list_with_resources
# Your Information
## Your Name

Dwi Febri S.
## Your Email

antoub@gmail.com
## Your Link

http://pakdhe.febri.web.id
**By submitting material in this issue you agree to:**

A. The terms of use - https://okfn.org/terms-of-use/

B. To place your contribution in the public domain (specifically you "license" any rights you may have under the CCZero - http://creativecommons.org/publicdomain/zero/1.0/ and/or the Open Data Commons Public Domain Dedication and License - http://opendatacommons.org/licenses/pddl/1.0/).

This latter enables us, in turn, to make available the resulting database openly available as per the Open Definition - http://opendefinition.org/od/.

**Comment by Mikanebu** [comment]
FIXED in this PR https://github.com/okfn/dataportals.org/pull/158
