### ISSUE TITLE
Wrong nationality of two portals

### ISSUE THREAD

**Issue by sharkbatt** [okfn/dataportals.org#125]
I found that the map of dataportals.org main page shows **wrong location of two portals**

This is **important** because the map **shows wrong nation** and both portals are **South Korea's** **government-run portal**. **NOT North Korean.**

**1. 'data.go.kr'**
url : data.go.kr
dataportals.org url : http://dataportals.org/portal/data_go_kr
**location : Daegu, South Korea(Rep. of Korea)**
latitude : 35.880886
longitude : 128.730030

**2.'datahub.kr'**
url : datahub.kr
dataportals.org url : http://dataportals.org/portal/korea-datahub
**location : Seoul, South Korea(Rep. of Korea)**
latitude : 37.566524
longitude : 126.977936

Please check and correct this as soon as possible.

**Comment by todrobbins** [comment]
Good catch @sharkbatt! I'll get those updated ASAP.
