### ISSUE TITLE
GeoBolivia

### ISSUE THREAD

**Issue by rafemoro** [okfn/dataportals.org#126]
`* Required`

# Key Data Portal Information
---
## Description * Open Geographic Data Portal

# Additional Information
## License details
La presente Declaración promueve el uso y reutilización de los conjuntos de datos abiertos bajo las siguientes libertades y condiciones:

1. Usted es libre de:

- Hacer, publicar y distribuir copias del conjunto de datos;
- Adaptar, remezclar y/o transformar el conjunto de datos;
- Extraer total o parcialmente contenido del conjunto de datos;
- Crear conjuntos de datos derivados del conjunto de datos o su contenido;

2. Siempre y cuando cumpla con las siguientes condiciones:

- Citar la fuente de origen de donde obtuvo el conjunto de datos,
- En el caso de copiar, distribuir, remezclar, modificar y crear a partir de un conjunto de datos y sus resultados, se mantengan la mismas libertades y condiciones de la presente Declaración.

3. Los portales e iniciativas de datos abiertos de gobierno deben hacer uso de la presente Declaración de uso de datos abiertos que garantiza la atribución de la autoría de los conjuntos de datos y velar por el carácter abierto de los mismos.

## Portal Software details 
geOrchestra provides independant and interoperable modules to build your own custom spatial data infrastructure:

- a data catalog based on GeoNetwork version 3.0.4,
- a map and feature server: GeoServer version 2.8.2,
- an advanced data access list manager: GeoFence,
- a map tiles server: GeoWebCache version 1.8.0,
- an advanced web map viewer with query, styling, editing functions,
- a data extractor to extract, reproject and download datasets from OGC services,
- a user and group manager (“ldapadmin”),
- a module to display data usage statistics (“analytics”).

License

All geOrchestra modules are available under the terms of the GNU GPL v3 license, except:
JASIG CAS - Apache License, version 2.0,
GeoNetwork & GeoServer - GPL v2,
GeoWebCache - LGPL.
Our main libraries are using a mix of licenses, compatible with the Open Source definition:
GeoTools - LGPL,
OpenLayers & GeoExt - BSD-style,
ExtJS - GPL v3,
proj4js - MIT.
Web Services

A geOrchestra platform advertises standard web services to discover (CSW), view (WMS, WMTS), symbolize (SLD), query and download (WFS), edit (WFS-T), and even process (WPS) geographical features. It also provides powerful web applications making use of these services (and eventually combining them). It interoperates perfectly with GIS softwares such as QGIS and ArcGIS.

## Full metadata download http://geo.gob.bo/geonetwork/srv/spa/catalog.search#/home

# Your Information
## Your Link https://goo.gl/H7OJHR

**By submitting material in this issue you agree to:**

A. The terms of use - https://okfn.org/terms-of-use/

B. To place your contribution in the public domain (specifically you "license" any rights you may have under the CCZero - http://creativecommons.org/publicdomain/zero/1.0/ and/or the Open Data Commons Public Domain Dedication and License - http://opendatacommons.org/licenses/pddl/1.0/).

This latter enables us, in turn, to make available the resulting database openly available as per the Open Definition - http://opendefinition.org/od/.

**Comment by Mikanebu** [comment]
FIXED, it was added in this PR https://github.com/okfn/dataportals.org/pull/159
