### ISSUE TITLE
Open Data Portal, Government of Telangana, India

### ISSUE THREAD

**Issue by Suryakandukuri** [okfn/dataportals.org#130]
`* Required`

# Key Data Portal Information
---
## Description * The Open Data Platform supports the 'Open Data Policy' of the Government of Telangana. The portal will be the central repository of all the datasets of the Government of Telangana that should be in the public domain. The portal will house datasets form the various departments and organizations of the Government of Telangana. The portal could be used by a variety of stakeholders and will enhance transparency in the working of the government apart from triggering innovative solutions to various problems.

# Additional Information
## Launched 05/15/2017
Date format: mm/dd/yyyy
-->

## Full metadata download

# Your Information
## Your Link data.telangana.gov.in

**By submitting material in this issue you agree to:**

A. The terms of use - https://okfn.org/terms-of-use/

B. To place your contribution in the public domain (specifically you "license" any rights you may have under the CCZero - http://creativecommons.org/publicdomain/zero/1.0/ and/or the Open Data Commons Public Domain Dedication and License - http://opendatacommons.org/licenses/pddl/1.0/).

This latter enables us, in turn, to make available the resulting database openly available as per the Open Definition - http://opendefinition.org/od/.

**Comment by Mikanebu** [comment]
FIXED, it was added in this PR https://github.com/okfn/dataportals.org/pull/159
