### ISSUE TITLE
Add a CKAN data portal in Hong Kong

### ISSUE THREAD

**Issue by howawong** [okfn/dataportals.org#131]
`* Required`

# Key Data Portal Information
---
## URL 
http://data.g0vhk.io

## Manager
http://g0vhk.io

## Description 
A data portal operated by open data developer

# Additional Information
## Place *
"HKSAR, China"

## Country
HK

## License *
Creative Commons Attribution License (cc-by)

## License details
http://opendefinition.org/licenses/cc-by/

## Type *
Community

## Launched
01/01/2017

## Portal Software
CKAN

## API Type *
Not yet

## API Endpoint
http://data.g0vhk.io/api/

## Full metadata download
N/A

# Your Information
## Your Name
Ho Wa Wong

## Your Email
info@g0vhk.io

## Your Link
http://g0vhk.io

**By submitting material in this issue you agree to:**

A. The terms of use - https://okfn.org/terms-of-use/

B. To place your contribution in the public domain (specifically you "license" any rights you may have under the CCZero - http://creativecommons.org/publicdomain/zero/1.0/ and/or the Open Data Commons Public Domain Dedication and License - http://opendatacommons.org/licenses/pddl/1.0/).

This latter enables us, in turn, to make available the resulting database openly available as per the Open Definition - http://opendefinition.org/od/.

**Comment by Mikanebu** [comment]
FIXED, it was added in this PR https://github.com/okfn/dataportals.org/pull/159
