### ISSUE TITLE
Several initiatives present [CKAN / OKFN]

### ISSUE THREAD

**Issue by cafferata** [okfn/dataportals.org#132]
Hello,

I'm very curious why there are several iniatives from CKAN / OKFN for collecting CKAN / data portals right now? As far as I am familiar;
- https://github.com/okfn/dataportals.org/
- https://github.com/ckan/ckan-instances/

In addition, I see that other people have taken part in it;
- https://github.com/okfn/dataportals.org/issues/88 (@wfdd)

However, we had the same ideas from the Netherlands / data.overheid.nl, but before we started duplicating I was curious whether we could hook up to 1 central view. How do you see this? What, in your opinion, is a central place to discuss this?

Crosslinks:
- https://github.com/ckan/ckan-instances/issues/117
- https://github.com/okfn/dataportals.org/issues/132

**Comment by rufuspollock** [comment]
@cafferata first a big welcome and we'd welcome your and colleagues participation.

> I'm very curious why there are several iniatives from CKAN / OKFN for collecting CKAN / data portals right now? As far as I am familiar;

@cafferata this (dataportals.org) is the primary initiative for a comprehensive list of data portals - the ckan-instances was (and is I believe) more about providing some high quality examples for the CKAN community.

@cafferata we'd really welcome collaborators and we'd be happy to jointly work on this. It would also be easy to set up a mini-pipeline or API to pull out data you needed for any sub-map or similar ...

I'm also cc'ing @todrobbins is the primary maintainer of this project at present 😄

**Comment by cafferata** [comment]
Hi @rufuspollock, long time no speak! Do you still remember our meeting back then in Warschau, Polen (OGDCamp, October 2011)?

> @cafferata this (dataportals.org) is the primary initiative for a comprehensive list of data portals - the ckan-instances was (and is I believe) more about providing some high quality examples for the CKAN community.

If this is the case, why can't we add an extra option voor de CKAN showcases? Then we still can merge both data sources to one, so there is only one truth. :-)

> @cafferata we'd really welcome collaborators and we'd be happy to jointly work on this. It would also be easy to set up a mini-pipeline or API to pull out data you needed for any sub-map or similar ...

That's exactly the reason I opened this issue, now there are two source systems. So I couldn't choose ;-)

> I'm also cc'ing @todrobbins is the primary maintainer of this project at present 😄

Thanks for pointing this out! Will wait for @todrobbins his reaction on this topic.

**Comment by rufuspollock** [comment]
To confirm: this is the primary source system. This is the place to come and contribute 😄 

> If this is the case, why can't we add an extra option voor de CKAN showcases? Then we still can merge both data sources to one, so there is only one truth. :-)

Great idea - would you be up for doing the work to have that refactor work?

> Thanks for pointing this out! Will wait for @todrobbins his reaction on this topic.

You don't need to wait I think - you can be bold 😄

**Comment by todrobbins** [comment]
@cafferata thank you for bringing this to our attention! We'd love to unify the output of these projects so as to best serve the public. I agree with @rufuspollock that it makes the most sense to treat dataportals.org as the primary source system.

I would love your help as I am trying my best as a part-time maintainer.

Cheers!

**Comment by cafferata** [comment]
Hi @todrobbins, what can I do? I personally was thinking of trying to migrate both data sources to one. My preferred language is PHP, so is there any possibility that you take the refactoring work of dataportals.org after the migration of both data sources?

**Comment by rufuspollock** [comment]
@cafferata there should be no issues with frontend if you merge from the ckan list into the one here and observe the current metadata structure. If you want to change the metadata structure just propose that in advance so we can discuss and adjust.

Please dive in and get going 😄 (and I'm pretty sure @todrobbins will say similar things 😉 )

**Comment by rufuspollock** [comment]
@cafferata any updates here? If you want to have a chat @todrobbins (and I) hangout on https://gitter.im/okfn/chat.

I'm also going to close this issue now 😄
