### ISSUE TITLE
www.geoguyane.fr

### ISSUE THREAD

**Issue by GeoGuyane** [okfn/dataportals.org#134]
`* Required`

# Key Data Portal Information
---
## Geodata catalogue for the French Guiana are

# Additional Information
## http://geoguyane.fr/geonetwork/srv/fre/csw-geoguyane?

# Your Information
## Your Link

**By submitting material in this issue you agree to:**

A. The terms of use - https://okfn.org/terms-of-use/

B. To place your contribution in the public domain (specifically you "license" any rights you may have under the CCZero - http://creativecommons.org/publicdomain/zero/1.0/ and/or the Open Data Commons Public Domain Dedication and License - http://opendatacommons.org/licenses/pddl/1.0/).

This latter enables us, in turn, to make available the resulting database openly available as per the Open Definition - http://opendefinition.org/od/.

**Comment by Mikanebu** [comment]
FIXED, it was added in this PR https://github.com/okfn/dataportals.org/pull/159
