### ISSUE TITLE
New portal registration

### ISSUE THREAD

**Issue by LJov** [okfn/dataportals.org#135]
`* Required`

# Key Data Portal Information
---
## Title *
 Open Data Macedonia - Official National Portal

## URL *
 http://www.otvorenipodatoci.gov.mk

## Manager
 Ministry of Information Society and Administration

## Description *

Open data is created by governmental agencies and institutions of the public sector in the process of their operations. The data is publicly available in order to enable their use by natural and legal entities for generation of new information, content, applications and services.

# Additional Information
## Place *
 Macedonia

## Country
 MK

## License *
 Free usage

## Type *
 Government.

## Launched
 01/01/2014

## API Type *
 None

## Full metadata download

# Your Information
## Your Name
 Luka J

## Your Email
 bckupadd@gmail.com

## Your Link

**By submitting material in this issue you agree to:**

A. The terms of use - https://okfn.org/terms-of-use/

B. To place your contribution in the public domain (specifically you "license" any rights you may have under the CCZero - http://creativecommons.org/publicdomain/zero/1.0/ and/or the Open Data Commons Public Domain Dedication and License - http://opendatacommons.org/licenses/pddl/1.0/).

This latter enables us, in turn, to make available the resulting database openly available as per the Open Definition - http://opendefinition.org/od/.

**Comment by Mikanebu** [comment]
FIXED, it was added in this PR https://github.com/okfn/dataportals.org/pull/159
