### ISSUE TITLE
National Statistic Service of Armenia

### ISSUE THREAD

**Issue by anihovh** [okfn/dataportals.org#136]
`* Required`

# National Statistic Service of Armenia
---
## Title *
Armstat.am - National Statistic Service of Republic of Armenia

## URL *
http://armstat.am/en/ 

## Manager
National Statistical Service

## Description *
It collects, processes and publishes statistical data in co-operation with state and local self-government bodies in the collection of statistical information.

# Additional Information
## Place *
Yerevan, Armenia

## Country
 Armenia 

## License *
 Official website 

## Type *
 Government 

## Launched
10/04/2017

## API Type *
unknown

## Full metadata download

# Your Information
## Your Name
Ani Hovhannisyan

## Your Email
anihovh@gmail.com 

## Your Link

**By submitting material in this issue you agree to:**

A. The terms of use - https://okfn.org/terms-of-use/

B. To place your contribution in the public domain (specifically you "license" any rights you may have under the CCZero - http://creativecommons.org/publicdomain/zero/1.0/ and/or the Open Data Commons Public Domain Dedication and License - http://opendatacommons.org/licenses/pddl/1.0/).

This latter enables us, in turn, to make available the resulting database openly available as per the Open Definition - http://opendefinition.org/od/.

**Comment by Mikanebu** [comment]
FIXED, it was added in this PR https://github.com/okfn/dataportals.org/pull/159
