### ISSUE TITLE
Add Serbian Open Data Portal

### ISSUE THREAD

**Issue by smarkovic** [okfn/dataportals.org#137]
`* Required`

# Key Data Portal Information
---
## Title *
Serbian Open Data Portal

## URL *
https://data.gov.rs

## Manager
Office for Information Technology and Electronic Government

## Description *

# Additional Information
## Place *
Serbia

## Country
RS

## License *
https://data.gov.rs/terms/

## Type *
Government

## Launched
02/15/2017

## Portal Software
uData

## API Type *
https://data.gov.rs/apidoc

## API Endpoint
https://data.gov.rs/apidoc

## Full metadata download
https://data.gov.rs/apidoc

# Your Information
## Your Name
Slobodan Markovic

## Your Email
smarkovic@netcentar.org

## Your Link
https://www.linkedin.com/in/smarkovic/

**By submitting material in this issue you agree to:**

A. The terms of use - https://okfn.org/terms-of-use/

B. To place your contribution in the public domain (specifically you "license" any rights you may have under the CCZero - http://creativecommons.org/publicdomain/zero/1.0/ and/or the Open Data Commons Public Domain Dedication and License - http://opendatacommons.org/licenses/pddl/1.0/).

This latter enables us, in turn, to make available the resulting database openly available as per the Open Definition - http://opendefinition.org/od/.

**Comment by Mikanebu** [comment]
FIXED, it was added in this PR https://github.com/okfn/dataportals.org/pull/159
