### ISSUE TITLE
Catalog.industrie.gov.tn

### ISSUE THREAD

**Issue by kimoensi** [okfn/dataportals.org#138]
`* Required`

# Key Data Portal Information
---
## Description *

# Additional Information
## Full metadata download

# Your Information
## Your Link

**By submitting material in this issue you agree to:**

A. The terms of use - https://okfn.org/terms-of-use/

B. To place your contribution in the public domain (specifically you "license" any rights you may have under the CCZero - http://creativecommons.org/publicdomain/zero/1.0/ and/or the Open Data Commons Public Domain Dedication and License - http://opendatacommons.org/licenses/pddl/1.0/).

This latter enables us, in turn, to make available the resulting database openly available as per the Open Definition - http://opendefinition.org/od/.

**Comment by rufuspollock** [comment]
@todrobbins are you able to review and merge these?

**Comment by todrobbins** [comment]
@rufuspollock I've been a bit overwhelmed as of late, but will prioritize all of these unless someone else wants to jump on the task.

**Comment by rufuspollock** [comment]
@todrobbins it would be great if you could look at these and get them in. I wonder if we also encourage people to PRs direct against the CSV for easy merging.

**Comment by Mikanebu** [comment]
FIXED, it was added in this PR https://github.com/okfn/dataportals.org/pull/159
