### ISSUE TITLE
LINZ Data Service

### ISSUE THREAD

**Issue by palmerj** [okfn/dataportals.org#139]
# Key Data Portal Information
---
## Title *
LINZ Data Service

## URL *
https://data.linz.govt.nz

## Manager
Land Information New Zealand - Is the public service department of New Zealand charged with geographical information and surveying functions as well as handling land titles, and managing Crown land and property.

## Description *
Free online access to New Zealand’s most up-to-date land and seabed data.

# Additional Information
## Place *
New Zealand

## Country
NZ

## License *
Most of the LINZ datasets are free to use and are available under an open Creative Commons Attribution license.

## License details
Almost all data from the LINZ Data Service is provided under the [Creative Commons Attribution 3.0 New Zealand licence](https://creativecommons.org/licenses/by/3.0/nz/). See more information here https://www.linz.govt.nz/data/licensing-and-using-data

## Type *
Government

## Launched
01/07/2011

## Portal Software
Other

## Portal Software details
Koordinates Enterprise. See https://koordinates.com/about for more information.

## API Type *
OGC Open Geospatial APIs. LINZ provide many service APIs for metadata, data and mapping services. These include OGC WFS, WC-S, WMS, WMTS. See https://www.linz.govt.nz/data/linz-data-service/guides-and-documentation/which-web-service-should-i-use for more information 

## API Endpoint
https://data.linz.govt.nz/services/

## Full metadata download
https://data.linz.govt.nz/services/csw/?service=CSW&version=2.0.2&request=GetRecords&ElementSetName=full&resultType=results&typeNames=csw:Record&outputFormat=application/xml

# Your Information
## Your Name
Jeremy Palmer

## Your Email
customersupport@linz.govt.nz

## Your Link
https://www.linz.govt.nz

**By submitting material in this issue you agree to:**

A. The terms of use - https://okfn.org/terms-of-use/

B. To place your contribution in the public domain (specifically you "license" any rights you may have under the CCZero - http://creativecommons.org/publicdomain/zero/1.0/ and/or the Open Data Commons Public Domain Dedication and License - http://opendatacommons.org/licenses/pddl/1.0/).

This latter enables us, in turn, to make available the resulting database openly available as per the Open Definition - http://opendefinition.org/od/.

**Comment by Mikanebu** [comment]
FIXED, it was added in this PR https://github.com/okfn/dataportals.org/pull/159
