### ISSUE TITLE
Lincolnshire Open Data

### ISSUE THREAD

**Issue by Lincolnshire-Open-Data** [okfn/dataportals.org#140]
`* Required`

# Key Data Portal Information
---
## Description *

# Additional Information
## Full metadata download

# Your Information
## Your Link

**By submitting material in this issue you agree to:**

A. The terms of use - https://okfn.org/terms-of-use/

B. To place your contribution in the public domain (specifically you "license" any rights you may have under the CCZero - http://creativecommons.org/publicdomain/zero/1.0/ and/or the Open Data Commons Public Domain Dedication and License - http://opendatacommons.org/licenses/pddl/1.0/).

This latter enables us, in turn, to make available the resulting database openly available as per the Open Definition - http://opendefinition.org/od/.

**Comment by todrobbins** [comment]
@Lincolnshire-Open-Data thank you for submitting, but I don't see any details in this issue. Could you edit your submission?

**Comment by Lincolnshire-Open-Data** [comment]
Thanks Tod,
I think the details are completed, but doesn't display in Preview (?)
Have removed the comment markers
Hope this ok, but if anything not completed please let us know
Many thanks
Kind regards,
Graham Williams
Reporting & Data Analyst,
Business Intelligence team, Lincolnshire County Council





`* Required`

# Key Data Portal Information
---
## Title* Lincolnshire Open Data

## URL*
www.lincolnshire.gov.uk/opendata

## Manager
Lincolnshire County Council

## Description *
The Lincolnshire Open Data portal from Lincolnshire County Council is the place for the public, researchers and developers to obtain data they can use in innovative ways, free of charge. -->

# Additional Information
## Place *
Lincolnshire

## Country


## License *
UK Open Government Licence

## License details


## Type *
UK Local Government: Lincolnshire County Council

## Launched
03/22/2017

## Portal Software
CKAN

## Portal Software details


## API Type *
CKAN

## API Endpoint
https://lincolnshire.ckan.io/api/3

## Full metadata download


# Your Information
## Your Name
Business Intelligence team, Lincolnshire County Council

## Your Email
opendata@lincolnshire.gov.uk

## Your Link
www.lincolnshire.gov.uk/opendata

**By submitting material in this issue you agree to:**

A. The terms of use - https://okfn.org/terms-of-use/

B. To place your contribution in the public domain (specifically you "license" any rights you may have under the CCZero - http://creativecommons.org/publicdomain/zero/1.0/ and/or the Open Data Commons Public Domain Dedication and License - http://opendatacommons.org/licenses/pddl/1.0/).

This latter enables us, in turn, to make available the resulting database openly available as per the Open Definition - http://opendefinition.org/od/.

**Comment by Lincolnshire-Open-Data** [comment]
Apologies Tod - I didn't realise 'Close' would close this thread, & have reopened it.  Please feel free to use our email for communications.  Many thanks.
Kind regards, Graham

**Comment by Lincolnshire-Open-Data** [comment]
Hi Tod,
Please feel free to let us know if we need to do anything further in order to publish the Lincolnshire Open Data site at http://dataportals.org
Many thanks
Kind regards,
Graham Williams
Reporting & Data Analyst
Business Intelligence team, Lincolnshire County Council

**Comment by Lincolnshire-Open-Data** [comment]
Hi Tod,
I'm sorry but we don't seem to have succeeded yet in getting details of the Lincolnshire Open Data portal published at http://dataportals.org.  Please feel free to let us know if we need to do anything further for information about the Lincolnshire Open Data site to be published.
Many thanks
Kind regards,
Graham Williams
Reporting & Data Analyst
Business Intelligence team, Lincolnshire County Council

**Comment by rufuspollock** [comment]
@todrobbins are you able to deal with this?

/cc @jwyg would you be up for assisting here?

**Comment by Mikanebu** [comment]
FIXED, it was added in this PR https://github.com/okfn/dataportals.org/pull/159
