### ISSUE TITLE
Incorrect link to North Devon Council Open Data

### ISSUE THREAD

**Issue by kneeboarder** [okfn/dataportals.org#141]
`* Required`

# Key Data Portal Information
---
## Title *
North Devon Council Open Data

## URL *
http://dataportals.org/portal/north_devon_council

## Manager
Vicky Eagle, North Devon Council

## Description *
URL is currently:

http://www.northdevon.gov.uk/index/lgcl_council_government_and_democracy/nonlgcl_open_data.htm

Needs to be changed to:

https://www.northdevon.gov.uk/council/data-protection-and-freedom-of-information/publication-scheme/open-data/

**Comment by Mikanebu** [comment]
FIXED, it was updated in this PR https://github.com/okfn/dataportals.org/pull/159

**Comment by kneeboarder** [comment]
Thank you very much :)
________________________________
