### ISSUE TITLE
data.culturecommunication.gouv.fr

### ISSUE THREAD

**Issue by jwyg** [okfn/dataportals.org#143]
`* Required`

# Key Data Portal Information
---
## Title *

data.culturecommunication.gouv.fr - la plate-forme de données ouvertes du ministère de la Culture

## URL *

http://data.culturecommunication.gouv.fr/

## Description *

# Additional Information
## Place *

France

## Country

FR

## Full metadata download

# Your Information
## Your Name

Jonathan Gray

## Your Link

**By submitting material in this issue you agree to:**

A. The terms of use - https://okfn.org/terms-of-use/

B. To place your contribution in the public domain (specifically you "license" any rights you may have under the CCZero - http://creativecommons.org/publicdomain/zero/1.0/ and/or the Open Data Commons Public Domain Dedication and License - http://opendatacommons.org/licenses/pddl/1.0/).

This latter enables us, in turn, to make available the resulting database openly available as per the Open Definition - http://opendefinition.org/od/.

**Comment by Mikanebu** [comment]
FIXED, it was added in this PR https://github.com/okfn/dataportals.org/pull/159
