### ISSUE TITLE
NepalMap: Data about Nepal at your fingertips

### ISSUE THREAD

**Issue by ravinepal** [okfn/dataportals.org#147]
`* Required`

# Key Data Portal Information
---
## Title *

NepalMap.Org - Data about Nepal at your fingertips
## URL *

https://nepalmap.org/
## Manager

Code for Nepal
## Description *

Data is broken down by category: Demographics, education. Our library of charts gives you insight into data from the places you search. Look for them on profile pages. You can also embed the charts on your own site.

# Additional Information
## Place *

Nepal

## Country

Nepal
## License *

MIT License 

## Type *

NGO 
## Launched
 10/30/2016

## Portal Software

Djgano 

## Full metadata download

# Your Information
## Your Name

Ravi Kumar
## Your Email

contact@codefornepal.org
## Your Link

twitter.com/ravinepal
**By submitting material in this issue you agree to:**

A. The terms of use - https://okfn.org/terms-of-use/

B. To place your contribution in the public domain (specifically you "license" any rights you may have under the CCZero - http://creativecommons.org/publicdomain/zero/1.0/ and/or the Open Data Commons Public Domain Dedication and License - http://opendatacommons.org/licenses/pddl/1.0/).

This latter enables us, in turn, to make available the resulting database openly available as per the Open Definition - http://opendefinition.org/od/.

**Comment by Mikanebu** [comment]
FIXED, it was added in this PR https://github.com/okfn/dataportals.org/pull/159
