### ISSUE TITLE
Saudi Government Open Data Portal

### ISSUE THREAD

**Issue by AlrasheedA** [okfn/dataportals.org#151]
`* Required`

# Key Data Portal Information
---
## Title *

Saudi Government Open Data portal

## URL *

Data.Gov.SA

## Description *

The primary role of the portal is to publish datasets from ministries and government agencies in an open format, and make this data available to the public. The platform enables the public to have central point of access to find, download and use datasets generated by the ministries and governmental entities in the country

# Additional Information
## Place *

Saudi Arabia

## Country

SA

## License *

While not required, when using content, data, documentation, code, and related materials from data.gov.sa in your own work, we ask that proper credit be given. An example citation is provided below:
Data retrieved from data.gov.sa (http://www.data.gov.sa)

## Type *

Government

## API Type *

NA

## Full metadata download

# Your Information
## Your Name

Ahmed Alrasheed

## Your Email

Alrasheeda29@gmail.com

## Your Link

https://www.linkedin.com/in/ahmedalrasheed/

**By submitting material in this issue you agree to:**

A. The terms of use - https://okfn.org/terms-of-use/

B. To place your contribution in the public domain (specifically you "license" any rights you may have under the CCZero - http://creativecommons.org/publicdomain/zero/1.0/ and/or the Open Data Commons Public Domain Dedication and License - http://opendatacommons.org/licenses/pddl/1.0/).

This latter enables us, in turn, to make available the resulting database openly available as per the Open Definition - http://opendefinition.org/od/.

**Comment by todrobbins** [comment]
Merged #154 which addresses this submission
