### ISSUE TITLE
Lincolnshire Open Data - please amend details and add a Map Pin

### ISSUE THREAD

**Issue by Lincolnshire-Open-Data** [okfn/dataportals.org#167]
`* Required`

# Key Data Portal Information
---
## Title *
Lincolnshire Open Data

## URL *
www.lincolnshire.gov.uk/opendata

## Manager
Lincolnshire County Council

## Description *

Details of the Lincolnshire Open Data portal were added to the OKFN Dataportals.org site (GitHub #140 , with the help of Tod Robbins).

Please can 3 amendments be made to the published information:

1. Please remove the HTML Paragraph Tags from the text description of the Lincolnshire Open Data portal, at https://dataportals.org/search

2.  Please correct the URL Hyperlink to the Lincolnshire Open Data portal, at https://dataportals.org/portal/lincolnshire-open-data  .  The URL currently redirects incorrectly - it should direct users to  www.lincolnshire.gov.uk/opendata

3.  Please add a Map Pin to the main Map on the Homepage at https://dataportals.org/  for the Lincolnshire Open Data portal.  Its primary coverage is the Lincolnshire County Council local government administrative area in the UK  (in eastern England).  So a suitable location for a Map Pin would be about halfway between Lincoln and Skegness on the map (that is for example the town of Horncastle).

Many thanks in anticipation

Kind regards, Graham Williams
Reporting & Data Analyst
Business Intelligence team
Lincolnshire County Council

# Additional Information
## Place *
Lincolnshire County Council (UK local government administrative area)

## Country
United Kingdom

## License *
UK Open Government Licence (unless otherwise specified)

## Type *
UK Local Government

## Full metadata download

# Your Information
## Your Name
Lincolnshire Open Data (portal run by Lincolnshire County Council)

Contact details (please keep Private):
Graham Williams
Reporting & Data Analyst
Business Intelligence team
Lincolnshire County Council
UK

## Your Email
opendata@lincolnshire.gov.uk

## Your Link
www.lincolnshire.gov.uk/opendata

**By submitting material in this issue you agree to:**

A. The terms of use - https://okfn.org/terms-of-use/

B. To place your contribution in the public domain (specifically you "license" any rights you may have under the CCZero - http://creativecommons.org/publicdomain/zero/1.0/ and/or the Open Data Commons Public Domain Dedication and License - http://opendatacommons.org/licenses/pddl/1.0/).

This latter enables us, in turn, to make available the resulting database openly available as per the Open Definition - http://opendefinition.org/od/.

**Comment by augusto-herrmann** [comment]
@Lincolnshire-Open-Data thanks for your submission for improving the data and sorry for taking so long to address this. This project is maintained in a voluntary basis and it is often the case that no one is available to work on it.

I must say, however, that if you would like us to include a map pin, please include the geographical coordinates (latitude and longitude) where the pin should be placed.

**Comment by Lincolnshire-Open-Data** [comment]
Hi Augusto,

Thank you for your message, and for amending the entry for the Lincolnshire Open Data portal

Please can a pin be added onto the map for it? The Lat/Long coordinates for it are:
Lat (WGS84)         N53:12:26 (53.20732522553808)
Long (WGS84)        W0:06:45 (-0.1124832197541849)
Lat,Long (WGS84)    53.20732522553808,-0.1124832197541849

This location (~Horncastle) is reasonably roughly approximate as a central-point for the area the portal covers

Many thanks for the voluntary support for this work - greatly appreciated

Graham Williams,
Reporting and Data Analyst,
Lincolnshire County Council

**Comment by augusto-herrmann** [comment]
Hi Graham (@Lincolnshire-Open-Data),

regarding the other 2 issues above,

> 1. Please remove the HTML Paragraph Tags from the text description of the Lincolnshire Open Data portal, at https://dataportals.org/search

I have just checked the page and see no *visible* HTML tags there, paragraph or otherwise:

![lincolnshire-2](https://user-images.githubusercontent.com/1058414/162847276-89f10378-58a7-48ca-9723-f610fb020ba8.png)

> 2. Please correct the URL Hyperlink to the Lincolnshire Open Data portal, at https://dataportals.org/portal/lincolnshire-open-data . The URL currently redirects incorrectly - it should direct users to [www.lincolnshire.gov.uk/opendata](http://www.lincolnshire.gov.uk/opendata)

I have just checked the page and the URL there is already exactly the one you are requesting: https://www.lincolnshire.gov.uk/opendata

![lincolnshire-3](https://user-images.githubusercontent.com/1058414/162847541-37add5e6-aa34-4236-bb9a-5e23e0379b44.png)

You can also check the [data file](https://github.com/okfn/dataportals.org/blob/master/data/portals.csv#L550) itself and see that there are no HTML tags at all in the description and that the URL is already the one requested.

So the only thing to here do is adding the coordinates for the map pin, which will be done by #262.
