### ISSUE TITLE
Download in bulk instructions on about page

### ISSUE THREAD

**Issue by rgrp** [okfn/dataportals.org#17]

**Comment by Stephen-Gates** [comment]
Add link to http://data.okfn.org/data/okfn/opendatasites to support bulk data download, exploring data and metadata. 

Update the data on http://data.okfn.org/data/okfn/opendatasites

**Comment by rgrp** [comment]
Now that we are storing the authoratative CSV here i think we should:

EITHER: deprecate and delete https://github.com/okfn/opendatasites and have everything here

OR move the data out of this repo to their and have this load from there.

Any preferences or thoughts on what is better @mattfullerton @Stephen-Gates 

My sense is that former is easier right now - whilst latter is a bit cleaner (and people can edit the data without having to get confused by all the webapp stuff)

**Comment by rgrp** [comment]
INVALID / FIXED / WONTFIX now we have download in the footer.
