### ISSUE TITLE
Serbiamap.Net

### ISSUE THREAD

**Issue by predragdukanac** [okfn/dataportals.org#170]
`* Required`

# Key Data Portal Information
---
## Title *
Serbiamap.Net

## URL *
(Serbian) http://serbiamap.net
(English) http://serbiamap.net/en/index.html

## Manager

Predrag Dukanac

## Description *

Serbiamap.Net introduces online interactive map of Republic of Serbia with map tile service.

# Additional Information
## Place *
Serbia (and surrounding countries)

## Country
RS (Serbia)

## License *

Proprietary, limited free service

## Type *
Company, non-profit

## Launched

06/01/2009

## Portal Software

ASP.NET

## API Type *

Web Tiles

## API Endpoint

Latin map: 'http://serbiamap.net/Tiles.ashx?z={z}&x={x}&y={y}', { maxZoom: 16, minZoom: 1 } );

Cyrillic map: 'http://serbiamap.net/Tiles.ashx?z={z}&x={x}&y={y}&lang=sr-cyrl', { maxZoom: 16, minZoom: 1 } );

## Full metadata download

# Your Information
## Your Name

Predrag Dukanac

## Your Email

predragdukanac@yahoo.com

## Your Link

**By submitting material in this issue you agree to:**

A. The terms of use - https://okfn.org/terms-of-use/

B. To place your contribution in the public domain (specifically you "license" any rights you may have under the CCZero - http://creativecommons.org/publicdomain/zero/1.0/ and/or the Open Data Commons Public Domain Dedication and License - http://opendatacommons.org/licenses/pddl/1.0/).

This latter enables us, in turn, to make available the resulting database openly available as per the Open Definition - http://opendefinition.org/od/.

**Comment by todrobbins** [comment]
Hi @predragdukanac,

Since this is a proprietary limited free service, it does not meet the requirements for dataportals.org. Thanks for submitting anyhow!
