### ISSUE TITLE
Add Portal https://www.realtyopendata.net on http://dataportals.org

### ISSUE THREAD

**Issue by rsipakov** [okfn/dataportals.org#179]
`* Required`

# Key Data Portal Information
---
## Title *
RealtyOpenData.NET

## URL *
https://www.realtyopendata.net

## Manager
Rostyslav Sipakov, Managing Partner at SVP4U

## Description *
RealtyOpenData.NET is empowering a new era of Real Estate industry by making it easy for anyone to publish, share, and discover content about investments, construction and design.
Our goal to build the world’s largest platform for interactive contents in Real Estate industry.
The mission of RealtyOpenData.NET is to innovate and challenge the limits of Real Estate market.
In addition to being the open data repository for everyone about Real Estate in the World, it includes data sets from many organizations in the Real Estate Industry.

# Additional Information
## Place *
International

## License *
Creative Commons Attribution License (cc-by)

## License details
http://opendefinition.org/licenses/cc-by/

## Type *
The portal operated for community

## Launched
12/01/2018

## Portal Software
CKAN

## API Type *
Socrata Open Data API (SODA)

## Full metadata download

# Your Information
## Your Name
Rostyslav Sipakov

## Your Email
 r.sipakov@svp4u.com

## Your Link
https://svp4u.com

**By submitting material in this issue you agree to:**

A. The terms of use - https://okfn.org/terms-of-use/

B. To place your contribution in the public domain (specifically you "license" any rights you may have under the CCZero - http://creativecommons.org/publicdomain/zero/1.0/ and/or the Open Data Commons Public Domain Dedication and License - http://opendatacommons.org/licenses/pddl/1.0/).

This latter enables us, in turn, to make available the resulting database openly available as per the Open Definition - http://opendefinition.org/od/.

**Comment by todrobbins** [comment]
The website doesn't load any longer. Do you have details on that @rsipakov?

**Comment by rsipakov** [comment]
Hey there,

We closed this projects.

Sincerely, 

Rostyslav

**Comment by todrobbins** [comment]
Thanks for the update!
