### ISSUE TITLE
Add goodtables.io continuous data validation

### ISSUE THREAD

**Issue by augusto-herrmann** [okfn/dataportals.org#186]
## Problem definition

Frequent editions with different tools make hard getting the `csv` files valid, as exemplified [here](https://github.com/okfn/dataportals.org/pull/182) and [here](https://github.com/okfn/dataportals.org/pull/172). Often pull requests have to be rebased and merged because of differences such as the handling of quotes or newlines.

## Proposed solution

Use continuous data validation do that PRs are checked and validated as soon as they are submitted. Make it automatic and part of the PR review process. [Goodtables.io](https://goodtables.io) is a service that provides continuous data validation for [Tabular Data Packages](https://frictionlessdata.io/specs/tabular-data-package/) under the [Frictionless Data](https://frictionlessdata.io/) program.

## Scope

The repository already does have a `datapackage.json` file. We need to check whether or not it does validate the `csv` files present and make adjustments where necessary so that the data validates. Add the repository to the Goodtables.io pipeline. Add a badge to the `README.md`. Make sure the validation is run upon receiving PRs.

**Comment by augusto-herrmann** [comment]
Solved with [PR#190](https://github.com/okfn/dataportals.org/pull/190).

**Comment by todrobbins** [comment]
Great work! Thanks @augusto-herrmann!
