### ISSUE TITLE
Lima portal not available

### ISSUE THREAD

**Issue by scrollif** [okfn/dataportals.org#198]
`* Required`

# Key Data Portal Information
---
## Description *

# Additional Information
## Full metadata download

# Your Information
## Your Link

**By submitting material in this issue you agree to:**

A. The terms of use - https://okfn.org/terms-of-use/

B. To place your contribution in the public domain (specifically you "license" any rights you may have under the CCZero - http://creativecommons.org/publicdomain/zero/1.0/ and/or the Open Data Commons Public Domain Dedication and License - http://opendatacommons.org/licenses/pddl/1.0/).

This latter enables us, in turn, to make available the resulting database openly available as per the Open Definition - http://opendefinition.org/od/.

**Comment by todrobbins** [comment]
@scrollif are you referring to http://dataportals.org/portal/datos-abiertos-lima?

**Comment by augusto-herrmann** [comment]
@todrobbins do we have a policy on data portals that used to be available but no longer are?

**Comment by rufuspollock** [comment]
@augusto-herrmann i think we should create a status flag or similar or maybe an end date? wdyt @augusto-herrmann ?

**Comment by augusto-herrmann** [comment]
@rufuspollock we [already do](https://github.com/okfn/dataportals.org/blob/master/data/datapackage.json#L94) have a status flag. End date could be nice if there was a reliable way of knowing it, but I don't think there is.

@scrollif, if you can confirm that you mean the URL mentioned by @todrobbins, we can mark this as "*inactive*".

**Comment by todrobbins** [comment]
I think this is the new Lima open data portal: https://www.datosabiertos.gob.pe/

**Comment by augusto-herrmann** [comment]
@todrobbins I think that is the national data portal of Peru. The issue is about the data portal of the city of Lima.

After a search, I've found this: http://datosabiertos.munlima.gob.pe/
Now all that is left is to replace the URL in the CSV.

**Comment by todrobbins** [comment]
Thanks! I can do that.

PS: something is still not working in the Heroku deployment process. The map disappeared again...

**Comment by todrobbins** [comment]
✅ [Fixed](https://github.com/okfn/dataportals.org/commit/47bc2abe5f4a9d77b6d58632fc56dbd2bc4ee1d0)
