### ISSUE TITLE
Javascript on the site not loading

### ISSUE THREAD

**Issue by augusto-herrmann** [okfn/dataportals.org#200]
None of the javascript files on the site are loading. They all return 404 errors. Because of that, the [map](22) and other functionality are no longer working.

Could it be due to the [free quota](161) having been exceeded on Heroku? @todrobbins @rufuspollock

**Comment by rufuspollock** [comment]
@augusto-herrmann i'm not sure - normally if free quota exceeded the site shuts down.

**Comment by augusto-herrmann** [comment]
We should have some tests and CI to track changes to the code of DataPortals.org and alert if there are any errors. We currently do have just a CI for the data using GoodTables.io, but not for the actual code (which brings me the question of whether or not we should separate the codebase for the site and the dataset in different repos. Wdyt, @rufuspollock ? ).

For now, I think we need someone who is familiar with the site's code or stack to take a look and find out why all the scripts are returning 404 errors.

**Comment by todrobbins** [comment]
@augusto-herrmann I think this might be my fault. I don't think the git submodules are being deployed via Heroku. I should have some time this week to troubleshoot if you're available.

**Comment by augusto-herrmann** [comment]
I have no experience deploying to Heroku or using the Heroku CLI, but, [from what I've glanced at](https://devcenter.heroku.com/articles/git), it does not seems to be difficult to do. So I'm up for it if I can help.

About the [git submodules](https://devcenter.heroku.com/articles/git-submodules), weren't they set up before? What has changed?

**Comment by augusto-herrmann** [comment]
When issuing the following command:

```
$ git submodule 
-fa5ff306740fffc17cd3c83d8c4121782ba66567 public/vendor/recline
```

we see only a submodule for Recline. What is the expected behaviour? Which submodules should be there?

I also tried checking out a commit of more than a year ago, and typing the same command. The result is exactly the same. So, I don't suppose some submodule has been excluded by accident. Am I looking in the correct places, @todrobbins ? As I said, I have no experience at all with submodules.

**Comment by rufuspollock** [comment]
@augusto-herrmann we're looking at this today on [Open Data Day](https://opendataday.org/). If you are around drop in to the channel here https://gitter.im/okfn/chat

**Comment by zelima** [comment]
@augusto-herrmann what exactly do you mean by  
>None of the javascript files on the site are loading. They all return 404 errors.

Just checked and most of them seem to be loading ok

- http://dataportals.org/js/catalog.js
- http://dataportals.org/js/app.js
- http://dataportals.org/vendor/backbone/0.5.1/backbone.js
- http://dataportals.org/vendor/backend.gdocs.js
- http://dataportals.org/vendor/bootstrap/3.3.7/js/bootstrap.js
- http://dataportals.org/vendor/mustache/0.5.0-dev/mustache.js
- http://dataportals.org/vendor/jquery/1.7.1/jquery.js
- http://dataportals.org/vendor/underscore/1.3.3/underscore.js

**Comment by zelima** [comment]
So I've removed recline to reproduce error locally...

I've created 2 new heroku apps and both work fine - maps are loading
1. run git submodle update before pushing to heroku https://mighty-island-21211.herokuapp.com/
2. just clone and push to heroku https://rocky-tor-25569.herokuapp.com/

Both loading maps. Probably simple redeploy to heroku will fix this

**Comment by rufuspollock** [comment]
@augusto-herrmann i also now definitively have heroku access and can share with others. Let's get this sorted!

**Comment by augusto-herrmann** [comment]
> @augusto-herrmann what exactly do you mean by
> 
> >   None of the javascript files on the site are loading. They all return 404 errors.
> 
> Just checked and most of them seem to be loading ok

You're right. What I meant to say is that a lot of the javascript files are not loading, especially the ones related to recline and leaflet.

![data-portals-errors](https://user-images.githubusercontent.com/1058414/76238542-c311a880-620e-11ea-8f27-013b0b24fece.png)

> @augusto-herrmann i also now definitively have heroku access and can share with others. Let's get this sorted!

Cool!

Sadly, the link to [Heroku deployment instructions on the README.md](/okfn/dataportals.org/blob/master/README.md#deployment) is now broken. It seems the Github repository `okfn/datasets.okfnlabs.org` no longer exists. @rufuspollock, do you know where that went?

As a side note, I've found this [article on containerizing Node.js apps](https://nodejs.org/en/docs/guides/nodejs-docker-webapp/#creating-a-dockerfile) that we might want to look into and implement in order to facilitate deployment using Docker.

**Comment by azolnai** [comment]
Hi, what's the status on the map front end? Thanks, Andrew

**Comment by todrobbins** [comment]
@rufuspollock @augusto-herrmann happy to help sort this out. I apologize for causing the issue in the first place!

**Comment by rufuspollock** [comment]
@toddrobbins - thanks, do you want to reproduce locally and see if you can
create a fix?

Rufus

**Comment by augusto-herrmann** [comment]
Thanks, @todrobbins !

From zelima's [comment above](#issuecomment-596072498) it should be simple to fix, but if you need my help fixing this, just say so.

**Comment by todrobbins** [comment]
✅ Fixed

<img width="952" alt="Screen Shot 2020-06-02 at 5 41 30 PM" src="https://user-images.githubusercontent.com/158590/83580069-500b8b80-a4f8-11ea-9034-fd365c91b47e.png">

Pushed the current GitHub `master` and we're good.

**Comment by azolnai** [comment]
Yay! Good work and thx, Andrew

**Comment by azolnai** [comment]
Hi, this front-end is broken again, shall I submit a new issue, or can you re-open this one?

![image](https://user-images.githubusercontent.com/12819663/96701726-d41bbe00-1388-11eb-9312-fccda97c017e.png)

**Comment by augusto-herrmann** [comment]
Indeed, it's broken again. Let's reopen.

**Comment by azolnai** [comment]
👍

**Comment by augusto-herrmann** [comment]
@todrobbins a lot of resource files are giving 404 errors again. Do you remember how you fixed it last time? I looked into the commit history and could not find any commits in June 2020, when you fixed it. So I suppose this is just some deployment issue?

You said last time you just manually deployed from `master`, but I just did that right now and it didn't make a difference.

**Comment by todrobbins** [comment]
@augusto-herrmann sorry for the delay! If I recall correctly I had to be sure to install the `git submodule` for `recline`. But I don't remember the command.

**Comment by augusto-herrmann** [comment]
@todrobbins I managed to install the `git submodule` for `recline` locally, but not on the Heroku deployment. There was supposed to be Heroku deployment instructions in the README, but they point to a broken link now (as an aside, I propose removing them for now, until we manage to write proper instructions #224).

Besides, `okfn/recline` has been renamed to [datopian/portal.js](https://github.com/datopian/portal.js), but I'm not sure it is a problem, as I was able to update the `git submodule` locally with the following command:

```bash
git submodule update --init --recursive
```

I found some [instruction on Heroku](https://devcenter.heroku.com/articles/git-submodules) on how to work with git submodules. However, these instructions there:

> Heroku properly resolves and fetches submodules as part of deployment:
> 
> ```
> git push heroku
> Counting objects: 13, done.
> ```

seem to be designed for a different kind of deployment. We're using automatic deploy from the `master` branch:

![heroku-automatic-deploy](https://user-images.githubusercontent.com/1058414/131897586-d5d36d33-9e24-4d3f-88a8-0660011f7293.gif)

and for some reason it seems it's not fetching the Recline submodule.

**Comment by todrobbins** [comment]
@rufuspollock care to lend a hand? 🙏🏻

**Comment by rufuspollock** [comment]
@todrobbins i'm not sure i have access to the heroku and i'm not very online atm. Is it worth asking e.g. @amercader?

**Comment by todrobbins** [comment]
No worries! Thanks for the reference!

**Comment by amercader** [comment]
Site seems up again, please check if everything works as expected.

I did two things:
1. Install [this buildpack](https://github.com/dmathieu/heroku-buildpack-submodules) to make sure git submodules are initialized on deploy (pretty sure this was unnecessary as the app had worked fine without it in the past)
2. Change the submodules config to point to a branch in the old recline repo (currently portal.js) that contained the actual recline code (https://github.com/okfn/dataportals.org/commit/b55023ed7537488966cdccf9e8f83749641bbb13). The renaming and reusing of the repository for a different purpose was what broke the build

**Comment by azolnai** [comment]
Thanks guys! I posted it on my SM. Andrew
https://twitter.com/azolnai/status/1437745413428240385?s=20

    On Tuesday, 14 September 2021, 10:50:04 BST, Adrià Mercader ***@***.***> wrote:  
 
 


Site seems up again, please check if everything works as expected.

I did two things:
   
   - Install this buildpack to make sure git submodules are initialized on deploy (pretty sure this was unnecessary as the app had worked fine without it in the past)
   - Change the submodules config to point to a branch in the old recline repo (currently portal.js) that contained the actual recline code (b55023e). The renaming and reusing of the repository for a different purpose was what broke the build

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by azolnai** [comment]
Thanks guys! I posted it on my SM s.a. below. Cheers, Andrew

https://twitter.com/azolnai/status/1437745413428240385?s=20

    On Tuesday, 14 September 2021, 10:50:04 BST, Adrià Mercader ***@***.***> wrote:  
 
 


Site seems up again, please check if everything works as expected.

I did two things:
   
   - Install this buildpack to make sure git submodules are initialized on deploy (pretty sure this was unnecessary as the app had worked fine without it in the past)
   - Change the submodules config to point to a branch in the old recline repo (currently portal.js) that contained the actual recline code (b55023e). The renaming and reusing of the repository for a different purpose was what broke the build

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by augusto-herrmann** [comment]
The site seems to be working properly for a while, now. Let's close this.

**Comment by azolnai** [comment]
Lookin' good, kid (apols 2 the Bogart)...
Thanks for restoring that! Call me an old sentimental who helped w this baby LOL

Sent from Yahoo Mail on Android 
 
  On Sun, 3 Jul 2022 at 1:14, Augusto ***@***.***> wrote:   


The site seems to be working properly for a while, now. Let's close this.
