### ISSUE TITLE
OPEN DATA PORTAL OF UZBEKISTAN

### ISSUE THREAD

**Issue by hurriyat1985** [okfn/dataportals.org#202]
`* Required`

# Key Data Portal Information
---
## Title *
 OPEN DATA PORTAL OF UZBEKISTAN 

## URL *
https://data.gov.uz/en 

## Manager
The State Committee of the Republic of Uzbekistan on Statistics 

## Description *
 This is the State information resource on the Internet, consisting of a set of software and hardware and is designed to accommodate a public government information in the form of open data 

# Additional Information
## Place *
Uzbekistan

## Country
UZ 

## License *
 Resolution of The President of the Republic of Uzbekistan “On additional measures to ensure openness and transparency of public administration, as well as to improve the statistical capacity of the country” dated April 9, 2019 №PP-4273. 
## License details
 https://lex.uz/docs/4277342 

## Type *
Is the portal operated by (and for) government (including IGOs such as World Bank or EC), research (academia), (other) institutional, or community? Yes 

## Launched
 30/03/2015

## Portal Software
Web frameworks Bootstrap 3.3.7 ,Yii. PHP 

## API Type *
The API Request home page is designed to provide information about the API, including reference information, terms of use, and a list of possible requests.

The query structure: «//api//»

• List of open data sets - the query is intended to obtain a list of open data sets.
The querystructure: «//api//»
• Open data set - the query is used to get a set of open data. The query structure:«//api///dataset/»
• List of open data set versions - the query is used to get a list of open data set versions. The query structure:
«//api///dataset//version»
• Open dataset version - the Query is designed to get complete information about the version of the open dataset. The query structure:
«//api///dataset//version\»
• Open data set version structure - the Query is designed to obtain complete information about the open data set version structure. The query structure:
«//api///dataset//version\/structure»
• The contents of the file version of the dataset Query is designed to retrieve the contents of the file version of the dataset. The query structure:
«//api///dataset//version\/content»
• List of organizations - the Request is intended to obtain a list of organizations registered on the portal that provide open data. The query structure:
«//api///organization»
• Organization - the Request is intended to obtain the full data of the organization providing open data. The query structure:
«//api///organization/»
• List of open data sets of the organization - the Query is intended to obtain a list of open data sets. The query structure:
«//api///organization//dataset»
• List of thematic headings - the Request is intended to obtain a list of thematic headings of open data sets. The query structure:
«//api///sphere»
• Thematic category - the Request is intended to obtain a thematic category. The query structure: «//api///sphere/»
• List of open data sets by thematic category - the Request is intended to obtain a list of open data sets by thematic category. The query structure:
«//api///shpere//dataset» 

## API Endpoint
http://data.gov.uz/uz/api/v1/json/dataset?access_key

## Full metadata download

# Your Information
## Your Name
Hurriyat Khudoykulova

## Your Email
opendata@stat.uz 

## Your Link
 https://data.gov.uz/en 

**By submitting material in this issue you agree to:**

A. The terms of use - https://okfn.org/terms-of-use/

B. To place your contribution in the public domain (specifically you "license" any rights you may have under the CCZero - http://creativecommons.org/publicdomain/zero/1.0/ and/or the Open Data Commons Public Domain Dedication and License - http://opendatacommons.org/licenses/pddl/1.0/).

This latter enables us, in turn, to make available the resulting database openly available as per the Open Definition - http://opendefinition.org/od/.

**Comment by augusto-herrmann** [comment]
Hi, @hurriyat1985, and thanks for your submission.

However, it looks like you didn't fill out the required fields, which are essential for including it in the database. Could you please edit your original post and add the required information? Otherwise we'll have to just close and dismiss the submission.

**Comment by hurriyat1985** [comment]
Hallo , Sir, thanks a lot for your regards.
We filled out required fields. Please, Could you check it once again? )

**Comment by hurriyat1985** [comment]
HI, DO SOMEBODY CAN CHECK OUR PORTAL AND SAY UZ SOME RESULTS PLEASE, WE ARE VERY LOOKING FORWARD YOU KINDLY ANSWER?

**Comment by augusto-herrmann** [comment]
Here's how to edit your original post:

1. scroll up to your first post;
2. click the three small dots in the upper right corner;
3. click “edit”;
4. write the text, making sure to fill out all fields that have an asterisk beside them (*);
5. click “save”.

**Comment by hurriyat1985** [comment]
Hallo, thanksss a lot for help and advise, Finally we got it ), and please check at once again . WE ARE VERY LOOKING FORWARD YOU KINDLY ANSWER? many thanks

**Comment by hurriyat1985** [comment]
Hallo Sir,
We filled out required fields. Please, Could you kindly check it once again? )
Thanking yours

**Comment by hurriyat1985** [comment]
> Here's how to edit your original post:
> 
> 1. scroll up to your first post;
> 2. click the three small dots in the upper right corner;
> 3. click “edit”;
> 4. write the text, making sure to fill out all fields that have an asterisk beside them (*);
> 5. click “save”.
Hallo, thanksss a lot for help and advise, Finally we got it ), and please check at once again . WE ARE VERY LOOKING FORWARD YOU KINDLY ANSWER? many thanks

**Comment by hurriyat1985** [comment]
DEAR EXPERTS,
 WHY ARE YOU NOT CHECKING OUR PORTAL, WHAT IS WRONG WITH IT NOW? CAN YOU PLEASE TAKE SOME TIME AND TELL US THE RESULTS. WE ARE VERY LOOKING FORWARD YOU KINDLY ANSWER? many thanks

**Comment by augusto-herrmann** [comment]
Solved by PR #210.
