### ISSUE TITLE
Reporting Accounts

### ISSUE THREAD

**Issue by adrianlawrence** [okfn/dataportals.org#203]
`* Required`

# Key Data Portal Information
---
## Title *
Reporting Accounts

## URL *
[](https://www.reportingaccounts.com)

## Manager
Compelling Media Ltd

## Description *
Free UK Company database covering more than 4 millions records

# Additional Information
## Place *
London, UK

## Country
GB

## License *
Open Government Licence v2.0.

## Type *
Community

## API Type *
No

## Full metadata download

# Your Information
## Your Name

Adrian Lawrence

## Your Email
adrianlawrence100@gmail.com

## Your Link

https://github.com/adrianlawrence
**By submitting material in this issue you agree to:**

A. The terms of use - https://okfn.org/terms-of-use/

B. To place your contribution in the public domain (specifically you "license" any rights you may have under the CCZero - http://creativecommons.org/publicdomain/zero/1.0/ and/or the Open Data Commons Public Domain Dedication and License - http://opendatacommons.org/licenses/pddl/1.0/).

This latter enables us, in turn, to make available the resulting database openly available as per the Open Definition - http://opendefinition.org/od/.

**Comment by rufuspollock** [comment]
Hi, this does not really seem like a proper data portal that would be suitable for dataportals.org. Thanks for submitting and good luck with the project.

**Comment by adrianlawrence** [comment]
https://dataportals.org/portal/bizdb-co-uk

Hi,

I based it on the above?

Thanks anyway

Adrian

**Comment by augusto-herrmann** [comment]
> https://dataportals.org/portal/bizdb-co-uk
> 
> Hi,
> 
> I based it on the above?
> 
> Thanks anyway
> 
> Adrian

I think that one should probably be removed as well, so I've created an issue to remind us to do it – #205. Thanks for pointing it out.
