### ISSUE TITLE
https://www.pariwartankhabar.com/ 

### ISSUE THREAD

**Issue by pariwartankhabar** [okfn/dataportals.org#204]
`* Required`

# Transforming lives through investigative and positive news. 
---
## Description *

# Additional Information ## Place * Kapan, Kathmandu 

## Full metadata download

# Your Information
## Your Link

**By submitting material in this issue you agree to:**

A. The terms of use - https://okfn.org/terms-of-use/

B. To place your contribution in the public domain (specifically you "license" any rights you may have under the CCZero - http://creativecommons.org/publicdomain/zero/1.0/ and/or the Open Data Commons Public Domain Dedication and License - http://opendatacommons.org/licenses/pddl/1.0/).
![pariwartankhabar editor](https://user-images.githubusercontent.com/35137345/72199896-bbca5a80-346a-11ea-8873-2610d00af061.jpg)
![pariwartankhabar interview studio](https://user-images.githubusercontent.com/35137345/72199897-bc62f100-346a-11ea-829d-20cbefca8812.JPG)
![Pariwartankhabar office building](https://user-images.githubusercontent.com/35137345/72199898-bc62f100-346a-11ea-92f5-d6867848b5ec.jpg)
![pariwartankhabar reception](https://user-images.githubusercontent.com/35137345/72199899-bcfb8780-346a-11ea-9cb8-01ca147a6802.JPG)
![pariwartankhabar studio](https://user-images.githubusercontent.com/35137345/72199900-bcfb8780-346a-11ea-948e-b2f265505ba8.JPG)

This latter enables us, in turn, to make available the resulting database openly available as per the Open Definition - http://opendefinition.org/od/.

**Comment by augusto-herrmann** [comment]
Hi, this does not really seem like a proper data portal that would be suitable for dataportals.org. Thanks for submitting and good luck with the project.
