### ISSUE TITLE
Remove bizdb-co-uk

### ISSUE THREAD

**Issue by augusto-herrmann** [okfn/dataportals.org#205]
As brought to our attention by @adrianlawrence, this does not seem to be an open data portal

https://dataportals.org/portal/bizdb-co-uk

and should likely be removed from Data Portals.

**Comment by rufuspollock** [comment]
@augusto-herrmann do you want to go ahead and remove it?

**Comment by adrianlawrence** [comment]
yes please

**Comment by augusto-herrmann** [comment]
Solved by PR #211.
