### ISSUE TITLE
THE STATE COMMITTEE OF THE REPUBLIC OF UZBEKISTAN ON STATISTICS

### ISSUE THREAD

**Issue by hurriyat1985** [okfn/dataportals.org#206]
`* Required`

# Key Data Portal Information
---
## Title *
The official website of THE STATE COMMITTEE OF THE REPUBLIC OF UZBEKISTAN ON STATISTICS" 

## URL *
https://stat.uz/en/

## Manager
THE STATE COMMITTEE OF THE REPUBLIC OF UZBEKISTAN ON STATISTICS 

## Description *
 The official website of the State Committee of the Republic of Uzbekistan on Statistics is an executive body of state power that implements a unified policy in the field of statistics. 

# Additional Information
## Place *
 Uzbekistan

## Country
UZ 

## License *
Attribution 4.0 International (CC BY 4.0).

## License details
 https://creativecommons.org/licenses/by/4.0/ 

## Type *
 Is the portal operated by (and for) government (including IGOs such as World Bank or EC), research (academia), (other) institutional, or community? Yes 

## Launched
March 23, 2006

## Portal Software
Web frameworks Bootstrap 3.3.7 ,Joomla, PHP 

## API Type *
Does the portal have any kind of API (structured metadata about the data that can be downloaded)? No 
Available bulk download 

## Full metadata download
https://stat.uz/en/open-data/181-ofytsyalnaia-statystyka-en/6405-31422343254

# Your Information
## Your Name
Hurriyat Khudoykulova

## Your Email
 opendata@stat.uz 

## Your Link
https://stat.uz/en/contacts1 

**By submitting material in this issue you agree to:**

A. The terms of use - https://okfn.org/terms-of-use/

B. To place your contribution in the public domain (specifically you "license" any rights you may have under the CCZero - http://creativecommons.org/publicdomain/zero/1.0/ and/or the Open Data Commons Public Domain Dedication and License - http://opendatacommons.org/licenses/pddl/1.0/).

This latter enables us, in turn, to make available the resulting database openly available as per the Open Definition - http://opendefinition.org/od/.

**Comment by todrobbins** [comment]
Hi @hurriyat1985, it looks like you didn't fill out any of the field which are required to get this submission added to dataportals.org. Please provide more info. 👍

**Comment by hurriyat1985** [comment]
Hallo , Sir, thanks a lot for your regards.
We filled out required fields. Please, Could you check it once again? )

**Comment by hurriyat1985** [comment]
HI, DO SOMEBODY CAN CHECK OUR PORTAL AND SAY UZ SOME RESULTS PLEASE, WE ARE VERY LOOKING FORWARD YOU KINDLY ANSWER?

**Comment by augusto-herrmann** [comment]
Hi, @hurriyat1985 . The fields marked with an asterisk (*) are required. I see they are still empty. Please edit your original post and fill them out before we can consider the submission, ok? :+1:

**Comment by hurriyat1985** [comment]
Hallo, thanksss a lot for help and advise, Finally we got it ), and please check at once again . WE ARE VERY LOOKING FORWARD YOU KINDLY ANSWER? many thanks

**Comment by hurriyat1985** [comment]
Dear Tod Robbins,
We would like to thank you for your supporting the efforts of countries, to improve their data systems and harness the advancements of the data revolution. We are determined to do whatever is necessary to ensure data provided by national statistical offices (NSOs) and other government organizations through principal open data portal.

**Comment by hurriyat1985** [comment]
we have studied this group in detail and there is no doubt that it is very important. but we would like to know more about this group. Please could you provide us  more information about the advantages  and opportunities that come with admission to dataportals.org. Many thanks )

**Comment by hurriyat1985** [comment]
Dear Tod Robbins,
WE SUBMITTED ONE MORE OPEN DATA PORTAL OF UZBEKISTAN (BELOW) BUT FOR A LONG TIME  NO ONE CHECKED IT AND ANSWERED.    CAN YOU PLEASE TAKE SOME TIME TO CHECK IT AND TELL US THE RESULTS. WE ARE VERY LOOKING FORWARD YOU KINDLY ANSWER? many thanks

**Comment by todrobbins** [comment]
@hurriyat1985 apologies for the delay! I have had a busy week with work and I'm just a volunteer. I'll get to it as soon as possible. ❤️

**Comment by hurriyat1985** [comment]
Thanks, You are the best! respect you !!!

**Comment by augusto-herrmann** [comment]
Solved by PR #210.
