### ISSUE TITLE
Idaho State Tax Commission open data portal submission

### ISSUE THREAD

**Issue by goo160047co** [okfn/dataportals.org#213]
Title *
Idaho State Tax Commission Taxing District Portal

URL *
https://gisdata-istc.opendata.arcgis.com/

Manager
Jeff Servatius

Description *
Dashboard of Taxing Districts in Idaho

Additional Information
Place *
Idaho

Country
US

License *
CC BY-SA 4.0

License details
Contains COGOed legal description information submitted by taxing districts. This data becomes valid in March of each year.

Type *
Open Data Commons Open Database License (ODbL) 

Launched
15/08/2020

Portal Software
arcgis.com

Portal Software details
API Type *
API Endpoint
Full metadata download
Your Information
Your Name
Idaho State Tax Commission GIS Department

Your Email
gis@tax.idaho.gov

Your Link
http://tax.idaho.gov/gis

By submitting material in this issue you agree to:

A. The terms of use - https://okfn.org/terms-of-use/

B. To place your contribution in the public domain (specifically you "license" any rights you may have under the CCZero - http://creativecommons.org/publicdomain/zero/1.0/ and/or the Open Data Commons Public Domain Dedication and License - http://opendatacommons.org/licenses/pddl/1.0/).

This latter enables us, in turn, to make available the resulting database openly available as per the Open Definition - http://opendefinition.org/od/

**Comment by todrobbins** [comment]
✅ [Added](http://dataportals.org/portal/idaho-tax)
