### ISSUE TITLE
Palestine Open Data Portal

### ISSUE THREAD

**Issue by abedkhooli** [okfn/dataportals.org#242]
`* Required`

# Key Data Portal Information
---
## Title *
Palestine Open Data Portal

## URL *
[Palestine Open Data Portal](http://www.opendata.ps/)

## Manager
Ministry of Telecom and IT

## Description *
A platform that offers (mostly) government and other institutions data in accordance with the Open Data Policy in Palestine - a framework for publishing (non-private) data that is open (technically and legally).

# Additional Information
## Place *
Jerusalem, Palestine

## Country
PS

## License *
Creative Commons Attribution

## License details
[CC-BY](https://opendefinition.org/licenses/cc-by/)](https://opendefinition.org/licenses/cc-by/)

## Type *
Government

## Launched
12/10/2021

## Portal Software
CKAN 2.9x

## API Type *
CKAN API 

## API Endpoint
[CKAN API 3](http://www.opendata.ps/api/3)

## Full metadata download

# Your Information
## Your Name
Abed Khooli

## Your Email
opendata@mtit.gov.ps

## Your Link
[Abed Khooli on Twitter](https://twitter.com/akhooli)

**By submitting material in this issue you agree to:**

A. The terms of use - https://okfn.org/terms-of-use/

B. To place your contribution in the public domain (specifically you "license" any rights you may have under the CCZero - http://creativecommons.org/publicdomain/zero/1.0/ and/or the Open Data Commons Public Domain Dedication and License - http://opendatacommons.org/licenses/pddl/1.0/).

This latter enables us, in turn, to make available the resulting database openly available as per the Open Definition - http://opendefinition.org/od/.

**Comment by augusto-herrmann** [comment]
Hi @abedkhooli, thanks for the submission!

Unfortunately a mandatory (and essential) field is missing: the URL of the portal. Without the URL it is impossible to link to it.

**Comment by abedkhooli** [comment]
Sorry, did not notice the first parts of markdown links. Link was there but without title. Edited the submission and hope it looks better now.

**Comment by augusto-herrmann** [comment]
@abedkhooli I've started PR #245, but I have so far left the `location` field blank, as I have no idea where to put this on a map. If you have lat/long coordinates for where you'd like the portal to display on a map, please say so.

**Comment by abedkhooli** [comment]
@augusto-herrmann 
Please use lat/long:
31.916873936677476, 35.213386165348155 
Many thanks.
Abed.
