### ISSUE TITLE
Open data portal for Urban Resarch - PPGAU UFF - Brazil

### ISSUE THREAD

**Issue by guilhermeiablo** [okfn/dataportals.org#251]
`* Required`

# Key Data Portal Information
---
## Title *
Portal de Dados Urbanos PPGAU UFF - Open data portal for Urban Resarch

## URL *
http://portaldados.ppgau.uff.br/

## Manager
Plano C (http://plano-c.com) and PPGAU-UFF

## Description *
Open data portal customized for urbanism and urban studies researchers.

# Additional Information
## Place *
Rio de Janeiro, Brazil

## Country
BR

## License *
CC

## Type *
Research

## Launched
03/01/2022

## Portal Software
Ubuntu 20.04, CKAN 2.9, Geoview, Spatial, Scheming

## Full metadata download

# Your Information
## Your Name
Guilherme Iablonovski

## Your Email
guilherme@plano-c.com

## Your Link
https://www.linkedin.com/in/guilhermeiablo/

**By submitting material in this issue you agree to:**

A. The terms of use - https://okfn.org/terms-of-use/

B. To place your contribution in the public domain (specifically you "license" any rights you may have under the CCZero - http://creativecommons.org/publicdomain/zero/1.0/ and/or the Open Data Commons Public Domain Dedication and License - http://opendatacommons.org/licenses/pddl/1.0/).

This latter enables us, in turn, to make available the resulting database openly available as per the Open Definition - http://opendefinition.org/od/.

**Comment by augusto-herrmann** [comment]
Thanks for your submission, @guilhermeiablo!

I'll add it when I have some time. Or, if you can create a pull request adding it to [data/portals.csv](/okfn/dataportals.org/blob/master/data/portals.csv), we could add it sooner.
