### ISSUE TITLE
Remove outdated shapefiles

### ISSUE THREAD

**Issue by augusto-herrmann** [okfn/dataportals.org#255]
[A zip file](/okfn/dataportals.org/blob/master/data/data.zip) with data in ESRI shapefile format is in the repository. This data is outdated (6 years old at the time of this writing). It also may cause confusion in users as whether to use it or `portals.csv`, the actual data file that is up-to-date.

Considering that, and that binary files are difficult to maintain in a git repository, I propose removing that file from this repo.

@azolnai feel free to comment if you or anyone else oppose this proposal.

**Comment by azolnai** [comment]
Yes please go ahead, that sounds reasonable. Andrew
    On Sunday, 3 April 2022, 17:56:27 BST, Augusto Herrmann ***@***.***> wrote:  
 
 


A zip file with data in ESRI shapefile format is in the repository. This data is outdated (6 years old at the time of this writing). It also may cause confusion in users as whether to use it or portals.csv, the actual data file that is up-to-date.

Considering that, and that binary files are difficult to maintain in a git repository, I propose removing that file from this repo.

@azolnai feel free to comment if you or anyone else oppose this proposal.
