### ISSUE TITLE
Tajikistan official government stats data portal

### ISSUE THREAD

**Issue by AlexandrKachko** [okfn/dataportals.org#266]
Here is another government data portal to enrich your records with sources from Central Asia: 

`* Required`

# Key Data Portal Information
---
## Title *

AGENCY ON STATISTICS UNDER PRESIDENT OF THE REPUBLIC OF TAJIKISTAN

## URL *

https://www.stat.tj/en

## Manager

The Statistical Agency under President of the Republic of Tajikistan

## Description *

The information in the Statistical Agency is prepared according to the program of statistical works and  Publication catalogue. The main publication of the Statistical Agency  is the monthly report  Socio-Economic Situation that includes the latest monthly data with brief commentary and is circulated to the offices of the President, Prime Minister and ministries and departments. This publication is available to the public. The report is published by the 12th day of the month following the accounting period. The annual publications also are issued: Statistical Yearbook of Tajikistan, Regions of Tajikistan, Tajikistan in figures and thematic publications.

# Additional Information
## Place *

Republic of Tajikistan

## Country

Tajikistan, TJK.

## License *

When using materials published on this site, a link to www.stat.tj is required.

## Type *

This site was developed within the framework of the ECASTAT project "Implementation of the National Strategy for Statistical Development"

## API Type *

Not that could be found there straightforwardly.

## Full metadata download

# Your Information
## Your Link

**By submitting material in this issue you agree to:**

A. The terms of use - https://okfn.org/terms-of-use/

B. To place your contribution in the public domain (specifically you "license" any rights you may have under the CCZero - http://creativecommons.org/publicdomain/zero/1.0/ and/or the Open Data Commons Public Domain Dedication and License - http://opendatacommons.org/licenses/pddl/1.0/).

This latter enables us, in turn, to make available the resulting database openly available as per the Open Definition - http://opendefinition.org/od/.

**Comment by augusto-herrmann** [comment]
Thanks for the submission, @AlexandrKachko.

I have looked around the site, but could only find PDF documents and data in HTML tables. Does it have data in a machine readable format, like, for example, `csv` or `json`, that make it easier for data users to reuse in spreadsheets or programming languages, without having the extra work to re-type or copy/paste whole tables?

**Comment by aivuk** [comment]
@augusto-herrmann  There are some Excel files (xlsx) if you go to the left menu in "Database" and "Analytical Tables".

**Comment by augusto-herrmann** [comment]
You are right, @aivuk. It wasn't working for me because I normally have scripts from Google blocked by default for privacy reasons. So clicking "Database" or "Analytical Tables" did not work.

When I enabled scripts originating from Google, those links to ".xlsx" files appeared. It is unfortunate that users have to send information to Google in order to have access to the data.
