### ISSUE TITLE
Include dadosjusbr

### ISSUE THREAD

**Issue by augusto-herrmann** [okfn/dataportals.org#276]
`* Required`

# Key Data Portal Information
---
## Title *

Dadosjusbr

## URL *

https://dadosjusbr.org/

## Manager

Universidade Federal de Campina Grande

## Description *

The portal consumes or scrapes data from several organizations of the Brazilian judiciary and public prosecution offices and reworks them using a common schema, making them easier to use for everyone and possible to compare to each other.

# Additional Information
## Place *

Brazil

## Country

BR

## License *

None

## License details

The license for the site and data collector code are MIT. A license for the data is not specified. Considering this is a third-party data publisher, the data license probably depends on the license specified by the original source, but the project does not inform that.

## Type *

Community

## Launched

I do not know when it launched. Can you please provide a date, @danielfireman?

## Portal Software

Custom/in-house

## Portal Software details

Open source MIT licensed available on https://github.com/dadosjusbr/site

## API Type *

I don't think it has an API. Does it, @danielfireman?

## Full metadata download

Is it possible to fully download everything in a single file, @danielfireman?

# Your Information
## Your Name

@augusto-herrmann (current maintainer of this repo)

## Your Link

**By submitting material in this issue you agree to:**

A. The terms of use - https://okfn.org/terms-of-use/

B. To place your contribution in the public domain (specifically you "license" any rights you may have under the CCZero - http://creativecommons.org/publicdomain/zero/1.0/ and/or the Open Data Commons Public Domain Dedication and License - http://opendatacommons.org/licenses/pddl/1.0/).

This latter enables us, in turn, to make available the resulting database openly available as per the Open Definition - http://opendefinition.org/od/.

**Comment by danielfireman** [comment]
Hi Augusto, good afternoon, and thanks for filing this issue!

Below I answer your questions and suggest some changes/improvements:

* **Title**: DadosJusBR
* **Manager**: It is currently managed by Instituto Federal de Alagoas (IFAL) in partnership with Transparência Brasil (TB)
* **Licence**: all provided packages are licensed under CC-BY-4.0
*  **License details**: we only scrape public government open data
* **Launched**: the first version of the website was launched at the end of 2018
* **API Type**: it has an API living at https://api.dadosjusbr.org/! Unfortunately, we still need to work on the documentation. Created https://github.com/dadosjusbr/api/issues/496 to track this effort

About this question:

> Full metadata download
> Is it possible to fully download everything in a single file, @danielfireman?

Are you asking about the metadata (datapackage.json) or all data we publish? The answer is yes to the former and currently no to the latter. It is worth noting that you could download all packages provided by DadosJusBR using the API.


cc/ @jeffersonrpn

**Comment by augusto-herrmann** [comment]
Thanks for all the information, @danielfireman!

Would you like to associate this portal to a particular point on the map?

If so, please provide the coordinates (latitude and longitude). Otherwise, I would just put it in Brasília, considering it is a country-wide project and Brasília is the capital.

**Comment by danielfireman** [comment]
> Thanks for all the information, @danielfireman!

You’re very welcome!

One small fix:

**Manager**: It is currently managed by Instituto Federal de Alagoas (IFAL) in partnership with Transparência Brasil (TB) and Universidade Federal de Campina Grande (UFCG)


> Would you like to associate this portal to a particular point on the map?
> 
> If so, please provide the coordinates (latitude and longitude). Otherwise, I would just put it in Brasília, considering it is a country-wide project and Brasília is the capital.


I believe it is totally fine to consider it a country-wide project.

**Comment by augusto-herrmann** [comment]
@danielfireman I have created a pull request (#279). Could you please check that the entry is correct?

**Comment by augusto-herrmann** [comment]
For lack of a better option I have put the geographical coordinates over the [National Council of Justice (CNJ)](https://www.openstreetmap.org/way/141122631#map=19/-15.74706/-47.89593) building. Even though the portal is an unofficial, community based effort, the data is related to the national judiciary and that is what I could think of. In other words, if an official effort to do the same thing was to happen, that would probably be the institution to do it.
