### ISSUE TITLE
Becoming an Editor (was: Adding new open data portals)

### ISSUE THREAD

**Issue by schlos** [okfn/dataportals.org#43]
Hi there,
Is anybody updating and adding new open data portals on the map? Ones submitted via Google Forms on dataportals.org.

Cheers!

**Comment by rgrp** [comment]
@schlos yes we are but we would also like an editorial help in doing this. Would you be interested in assisting (this would just mean subscribing to submissions on the form, reviewing and then copying to the main spreadsheet).

**Comment by schlos** [comment]
@rgrp sure, I can support you with this.

**Comment by rgrp** [comment]
@mattfullerton would you be able to brief @schlos ?

**Comment by mattfullerton** [comment]
@schlos Sure, just email or skype me (matt.fullerton@gmail.com works for both)

**Comment by rgrp** [comment]
@mattfullerton @schlos let me know how you get on.

**Comment by rgrp** [comment]
FIXED.
