### ISSUE TITLE
Upgrade Recline

### ISSUE THREAD

**Issue by sabas** [okfn/dataportals.org#46]
The used version includes an old Leaflet. Would be cool if you can upgrade to a commit after https://github.com/okfn/recline/pull/431

**Comment by mattfullerton** [comment]
I've done this (with the effect of Leaflet 0.4.4->0.7.3), but is it just me or is something not quite right with the clustering/zooming?

**Comment by sabas** [comment]
Could it possibly be that the clustering code should be tweaked between the old and the new version?

**Comment by mattfullerton** [comment]
Yes, the clustering module had not been updated in recline. Should all be working now.

**Comment by rgrp** [comment]
@mattfullerton great work!
