### ISSUE TITLE
Information box not processing markdown

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/dataportals.org#55]
Not sure if this is an error in the spreadsheet data or the information box.

Spreadsheet description column has cells with markdown. The information box does not process the markdown.
<img width="425" alt="screenshot 2015-08-21 20 58 14" src="https://cloud.githubusercontent.com/assets/9379524/9406930/11fa5752-4848-11e5-988b-3cc602b7d0bc.png">

Could be added to #37

**Comment by Stephen-Gates** [comment]
Looks like you need to use html not markdown http://leafletjs.com/reference.html#popup

**Comment by mattfullerton** [comment]
Yes, although it would be "no problem" to preprocess the markdown on the server side. I just have to do it :)
