### ISSUE TITLE
Catalog Software dropdown values in Form

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/dataportals.org#56]
What is `Option 10`?

What's the difference between:
- `CKAN based (including DKAN)`, and
- `DKAN`?

<img width="284" alt="screenshot 2015-08-21 21 32 26" src="https://cloud.githubusercontent.com/assets/9379524/9407420/59a686c6-484c-11e5-85ae-fb9feeaf7b39.png">

Does the set of valid values need to be refined?

**Comment by mattfullerton** [comment]
I would say DKAN and Option 10 can be removed. Although somehow I find it interesting to know how many people are using DKAN. We could do "CKAN based (excluding DKAN)" instead.

**Comment by Stephen-Gates** [comment]
Sounds good to me.

**Comment by jgkim** [comment]
Option 10 can be removed, but I think DCAN should be distinguished from CKAN so “CKAN (including DKAN)” should be just “DKAN.”

Technically speaking, as you know, DKAN’s code is not based on CKAN’s, even though DKAN’s features are modeled after CKAN’s. They are different products from different organizations.

**Comment by Stephen-Gates** [comment]
Ok thanks @jgkim. So: 

- CKAN
- DKAN

**Comment by Stephen-Gates** [comment]
Actually should we also add ArcGIS Open Data has it is becoming a common platform http://opendata.arcgis.com ?

**Comment by rgrp** [comment]
@Stephen-Gates did you make these changes. Also good to add ArcGIS if you want.

**Comment by Stephen-Gates** [comment]
@rgrp I didn't make the changes. I don't think validation was strongly implemented in the Google Sheet and as a new editor I wasn't confident to mess with it beyond curating entries.

**Comment by rgrp** [comment]
@Stephen-Gates I would go ahead and make the changes - and then we can trial and see if all still good.

**Comment by Stephen-Gates** [comment]
Done
