### ISSUE TITLE
Inconsistent use of Portal and Catalog in Form

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/dataportals.org#57]
The Add a Portal form interchanges the words "portal" and "catalog". We should be consistent and just use "portal". e.g.
<img width="329" alt="screenshot 2015-08-21 21 39 20" src="https://cloud.githubusercontent.com/assets/9379524/9407520/5a5e5d72-484d-11e5-84fb-edff59d1fb29.png">

**Comment by rgrp** [comment]
@Stephen-Gates do you want to go ahead and do this?

**Comment by rgrp** [comment]
@Stephen-Gates you have edit access.

**Comment by Stephen-Gates** [comment]
Done.
