### ISSUE TITLE
Website is offline

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/dataportals.org#59]
<img width="588" alt="screenshot 2015-10-13 19 39 57" src="https://cloud.githubusercontent.com/assets/9379524/10451229/41fd0512-71e2-11e5-9fa0-82bbb01b7a5f.png">

**Comment by mattfullerton** [comment]
Looks like the DNS isn't working any more. The app itself is up:
http://datacatalogs-org.herokuapp.com

@rgrp @danfowler Can you ping someone at OKF to check the DNS?

**Comment by danfowler** [comment]
Thanks for flagging. Looks like the registration expires today:

    Registry Expiry Date: 2015-10-13T04:58:42Z

Will get the support ticket out.

**Comment by mattfullerton** [comment]
Weird, I'd ruled that out because datacatalogs.org wasn't working either

**Comment by danfowler** [comment]
Back online! Thanks @nigelbabu :+1:
