### ISSUE TITLE
Switch to csv stored in github rather the google doc [discussion]

### ISSUE THREAD

**Issue by rgrp** [okfn/dataportals.org#61]
Proposal: move to CSV stored in github as backend for the site rather than google doc spreadsheet. 

Why?

* Allow much nicer contribution workflow - pull request review and merge
  * Right now it is painful because of limiting access to google docs

Aside:
* Could still keep google form for new portals for non-techies (?). Would require some editorial support.

## Implementation

Really easy as we just need to change point from one CSV to another.

* [x] Shut down editing / announce deprecation of the old spreadsheet
* [x] Pull data across into repo
* [ ] Switch code to load

**Comment by jgkim** [comment]
+1

**Comment by alexfriant** [comment]
+1
Moving the sheet to a CSV on github makes perfect sense.
