### ISSUE TITLE
Add Contribute page

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/dataportals.org#68]
As [discussed on the forum](https://discuss.okfn.org/t/moving-database-to-csv-in-github/1580/3?u=stephen), add a contribute page that provides instructions to:
- add a portal
- correct portal information
- add portals in bulk
- report an issue

[Draft content](https://docs.google.com/document/d/11QXUCjOlLSWmgbGahBPO_CLhc3EnkvqLXfShfmMBPsI/edit?usp=sharing) is in a google doc. Please request access if you'd like to edit.

**Comment by papajo** [comment]
I'd like to contribute. Please let me know if you need any help. Thanks. 
PJ.

**Comment by rgrp** [comment]
@papajo please can you request access to the doc Stephen prepared and review it. If it looks good we want to get it onto the website (see e.g. about page as an example of how we do that).

**Comment by papajo** [comment]
Hello, Stephen, may I please have access to the document so I can take a look? Thanks.

**Comment by Stephen-Gates** [comment]
@papajo I've sent you an invite to edit

**Comment by rufuspollock** [comment]
@papajo @Stephen-Gates it would be **great** to get this up. What happened with the review? I can help get this up when ready!

**Comment by todrobbins** [comment]
@Stephen-Gates @rufuspollock which document are you referring to? I'd love to have a look as well.

**Comment by todrobbins** [comment]
@rufuspollock @Stephen-Gates I'm working on the Contribute page now.

**Comment by todrobbins** [comment]
WIP screen grab:

![screen shot 2017-04-11 at 1 15 54 pm](https://cloud.githubusercontent.com/assets/158590/24926581/4ec088de-1eb9-11e7-9268-7d4e90a5af4a.png)

PS: this is shows an updated design bringing us up to Bootstrap 3.3.7

**Comment by todrobbins** [comment]
See #100 for review

**Comment by todrobbins** [comment]
Contribute page is live, will add more instructions soon.
