### ISSUE TITLE
Document CSV column headers

### ISSUE THREAD

**Issue by stevage** [okfn/dataportals.org#73]
Could there be at least a description of each column in the README?

I'll start:

* `name`: Short name for the catalog
* `title`: Longer name
* `url`: URL for the catalog's front page
* `author`: 
* `publisher`: 
* `issued`: Date the catalog was created, if known
* `publisher_classification`: Government/Institutional/...
* `description`: Free text summary of the catalog.
* `tags`:
* `license_id`: Primary licence used: cc-by, odc-odbl, other-open, other-closed, etc
* `license_url`:
* `place`: City/State/Country where the catalog's data comes from
* `location`: "lat,lon" format for the pin
* `country`: 2 digit country code
* `language`: Space-separated list of two-digit language codes
* `status`: active/inactive
* `metadatacreated`:
* `generator`:
* `api_endpoint`: URL of API endpoint
* `api_type`: CKAN API/Socrata Open Data API (SODA)/Junar API/...
* `full_metadata_download`

**Comment by Stephen-Gates** [comment]
@stevage see https://github.com/okfn/dataportals.org/blob/master/data/datapackage.json and #64. We're working on improving this - feel free to contribute.

**Comment by Stephen-Gates** [comment]
Thanks @stevage
