### ISSUE TITLE
Incorrect lat/long for portals at least in China

### ISSUE THREAD

**Issue by haoliangyu** [okfn/dataportals.org#76]
Most portals in China are actually foreign portals. For example, we have a Chinese City of Las Vegas portal. Not sure if it is a common problem for others portals. Any idea on how to fix this?

![screenshot from 2015-12-06 16-12-10](https://cloud.githubusercontent.com/assets/1726265/11615647/35cbde22-9c34-11e5-9cff-8d3d9487fc54.png)

**Comment by marks** [comment]
I noticed this and started to correct some in a pending pull request. The cause is missing negative signs before some of the latitude/longitude numbers 


--
Mark Silverberg
(m) 512 826 7004
http://twitter.com/skram

**Comment by marks** [comment]
@haoliangyu I just submitted a PR (https://github.com/okfn/dataportals.org/pull/77) to address some of these. I probably didnt get them all but its a start

**Comment by haoliangyu** [comment]
@marks That's awesome. I will also take a look at this when I have some free time.

**Comment by todrobbins** [comment]
@haoliangyu I know it's been over a year since this was discussed, but can you confirm whether the lat/lon of these data points has been corrected by @marks?

Cheers!

**Comment by haoliangyu** [comment]
@todrobbins Yes. Thanks for the reminder. I think I have totally forgotten this issue. Will check it after work.

**Comment by haoliangyu** [comment]
All portals in China are located correctly. This issue can be closed.
