### ISSUE TITLE
Direct tile access is disabled

### ISSUE THREAD

**Issue by miguelsalazar** [okfn/dataportals.org#87]
Map isn't rendered.

<img width="1237" alt="screen shot 2016-07-13 at 10 33 09 am" src="https://cloud.githubusercontent.com/assets/2068301/16809273/4d9e385c-48e5-11e6-822a-46335e1cb191.png">

**Comment by danfowler** [comment]
@miguelsalazar Thanks for flagging!

**Comment by mike-bailey** [comment]
Recommended alternative
https://carto.com/location-data-services/basemaps/

**Comment by danfowler** [comment]
Fixed: http://dataportals.org/

Thanks for the suggestion @mike-bailey but this tool gets its map magic from the Recline library: https://github.com/okfn/recline
