### ISSUE TITLE
review README and update project details/links

### ISSUE THREAD

**Issue by todrobbins** [okfn/dataportals.org#97]
- [ ] Check/update links
- [ ] Expand project description

**Comment by augusto-herrmann** [comment]
It seems that the only broken link is the one in the [Deployment](https://github.com/okfn/dataportals.org#deployment) section.

**Comment by augusto-herrmann** [comment]
@todrobbins I've addressed this in PR #257, except for the repository description. It seems I don't have the necessary permissions to change it.
