### ISSUE TITLE
Update curators list?

### ISSUE THREAD

**Issue by todrobbins** [okfn/dataportals.org#99]
How are we qualifying whether a DataPortals.org participant is a curator? [This list](http://dataportals.org/about) likely needs to be updated.

Where should we start?

**Comment by Stephen-Gates** [comment]
Hi Tod, from memory Rufus said these names needed to stay in some form due to how the project was originally funded but I don't believe these people continue to play a curation role.

**Comment by rufuspollock** [comment]
@todrobbins @Stephen-Gates that's right. If we wanted to update I think we could move what's currently there to a section of that page called "Historical" or similar.

**Comment by augusto-herrmann** [comment]
It seems that @todrobbins has already [done this](/okfn/dataportals.org/commit/0be75df233d1d68ad83109146b6a2001195169ae) in 2017, so I'm closing the issue.
